sudo: required
language: generic
services:
  - docker

before_install: 
  - docker build -t systtek/react-test -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true systtek/react-test npm run test -- --coverage